version: 2.1

orbs: 
  docker: circleci/docker@2.8.0
  ggshield: gitguardian/ggshield@1.1.4
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@5.2.0

jobs:

  test:
    docker:
      - image: thinxcloud/console-build-env:latest
    steps:
      - checkout

      # Install Node 25
      - node/install:
          node-version: '25.0'

      # Build deps for native modules (e.g., isolated-vm)
      - run:
          name: Ensure build deps (for isolated-vm)
          command: |
            apt-get update && apt-get install -y python3 make g++

      # Install deps with caching (replacement for node/with-cache)
      - node/install-packages:
          pkg-manager: npm
          app-dir: .
          override-ci-command: npm ci

      # Run tests
      - run:
          name: Run Tests
          no_output_timeout: 1m
          command: npm test

      # Upload coverage to Coveralls
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov.info
          verbose: true

workflows:

  build-and-publish:

    jobs:

      - test:
          context:
            - coveralls
            - rollbar

      - ggshield/scan:
          base_revision: << pipeline.git.base_revision >>
          revision: << pipeline.git.revision >>
          name: gitguardian
          context:
            - gitguardian

      - docker/publish:
          name: build and publish
          image: thinxcloud/transformer
          context:
            - dockerhub
            - rollbar
          requires:
            - test
