version: 2.1

orbs: 
  docker: circleci/docker@2.0.1
  ggshield: gitguardian/ggshield@1.1.0
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6

jobs:

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Run Tests
                no_output_timeout: 1m
                command: |
                  npm install
                  npm test
                  ls -la ./coverage
                  ls -la
            - coveralls/upload:
                path_to_lcov: ./coverage/lcov.info
                verbose: true

workflows:

  build-and-publish:

    jobs:

      - test:
          name: Run Tests and Submit Coverage
          context:
            - coveralls

      - ggshield/scan:
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>
          name: Scan using Gitguardian shield
          context:
            - gitguardian

      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/transformer
          context:
            - dockerhub
          requires:
            - Test