version: 2.1

orbs: 
  docker: circleci/docker@2.0.1
  ggshield: gitguardian/ggshield@1.1.0
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@5.0.0

jobs:

 install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '17'

  test:
    
    executor:
      name: node/default
    
    steps:

      - checkout
    
      - node/with-cache:
          steps:
            - run:
                name: Run Tests
                no_output_timeout: 1m
                command: |
                  cd app
                  npm install
                  npm test
            
      - coveralls/upload:
          parallel: true
          flag_name: API Tests
          verbose: true

workflows:

  build-and-publish:

    jobs:

      - ggshield/scan:
          name: Scan using Gitguardian shield
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>
          context:
            - gitguardian

      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/transformer
          context:
            - dockerhub

      - test:
          jobs:
            - install-node-example
            - test
          context:
            - coveralls