version: 2.1

orbs: 
  docker: circleci/docker@2.0.1
  ggshield: gitguardian/ggshield@1.1.0
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6

jobs:

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          # /with-cache
          steps:
            - run: |
                cd app
                npm install
                npm test
      - coveralls/upload:
          parallel: false
          flag_name: Test 2
          verbose: false

workflows:

  build-and-publish:

    jobs:

      - ggshield/scan:
          name: Scan using Gitguardian shield
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>
          context:
            - gitguardian

      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/transformer
          context:
            - dockerhub

      - test:
          context:
            - coveralls